package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.ActGeBytearray;

public interface ActGeBytearrayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insert(ActGeBytearray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insertSelective(ActGeBytearray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    ActGeBytearray selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKeySelective(ActGeBytearray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ActGeBytearray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKey(ActGeBytearray record);
}