package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.ActHiComment;

public interface ActHiCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insert(ActHiComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insertSelective(ActHiComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    ActHiComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKeySelective(ActHiComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ActHiComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKey(ActHiComment record);
}