package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.ActHiActinst;

public interface ActHiActinstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insert(ActHiActinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insertSelective(ActHiActinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    ActHiActinst selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKeySelective(ActHiActinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKey(ActHiActinst record);
}