package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.ActHiIdentitylink;

public interface ActHiIdentitylinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insert(ActHiIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insertSelective(ActHiIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    ActHiIdentitylink selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKeySelective(ActHiIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKey(ActHiIdentitylink record);
}