package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.ActHiVarinst;

public interface ActHiVarinstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insert(ActHiVarinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insertSelective(ActHiVarinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    ActHiVarinst selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKeySelective(ActHiVarinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKey(ActHiVarinst record);
}