package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.ActIdGroup;

public interface ActIdGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_group
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_group
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insert(ActIdGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_group
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insertSelective(ActIdGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_group
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    ActIdGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_group
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKeySelective(ActIdGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_group
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKey(ActIdGroup record);
}