package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.ActIdMembership;
import org.apache.ibatis.annotations.Param;

public interface ActIdMembershipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_membership
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("groupId") String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_membership
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insert(ActIdMembership record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_membership
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insertSelective(ActIdMembership record);
}