package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.ActRuIdentitylink;

public interface ActRuIdentitylinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_identitylink
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_identitylink
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insert(ActRuIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_identitylink
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insertSelective(ActRuIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_identitylink
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    ActRuIdentitylink selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_identitylink
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKeySelective(ActRuIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_identitylink
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKey(ActRuIdentitylink record);
}