package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.ActRuVariable;

public interface ActRuVariableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    int insert(ActRuVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    int insertSelective(ActRuVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    ActRuVariable selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    int updateByPrimaryKeySelective(ActRuVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    int updateByPrimaryKey(ActRuVariable record);
}