package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.ActRuAuthorization;

public interface ActRuAuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_authorization
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_authorization
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insert(ActRuAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_authorization
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int insertSelective(ActRuAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_authorization
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    ActRuAuthorization selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_authorization
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKeySelective(ActRuAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_authorization
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    int updateByPrimaryKey(ActRuAuthorization record);
}