package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.CnvDrug;

import java.util.List;

public interface CnvDrugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnv_drug
     *
     * @mbg.generated Tue Nov 07 15:47:08 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnv_drug
     *
     * @mbg.generated Tue Nov 07 15:47:08 CST 2023
     */
    int insert(CnvDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnv_drug
     *
     * @mbg.generated Tue Nov 07 15:47:08 CST 2023
     */
    int insertSelective(CnvDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnv_drug
     *
     * @mbg.generated Tue Nov 07 15:47:08 CST 2023
     */
    CnvDrug selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnv_drug
     *
     * @mbg.generated Tue Nov 07 15:47:08 CST 2023
     */
    int updateByPrimaryKeySelective(CnvDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnv_drug
     *
     * @mbg.generated Tue Nov 07 15:47:08 CST 2023
     */
    int updateByPrimaryKey(CnvDrug record);


    /**
     *
     * 自定义部分
     */

    List<String> getAllCnvDrug();

}
