package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.ExperimentData;

import java.util.List;
import java.util.Map;

public interface ExperimentDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_data
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_data
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    int insert(ExperimentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_data
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    int insertSelective(ExperimentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_data
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    ExperimentData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_data
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    int updateByPrimaryKeySelective(ExperimentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_data
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    int updateByPrimaryKey(ExperimentData record);

    /**
     *
     * 自定义部分
     */

    List<ExperimentData> getExperimentDataList(Map<String,Object> params);

    int getExperimentDataCount(Map<String,Object> params);
}
