package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.LabFridgeLevel;

import java.util.List;

public interface LabFridgeLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_fridge_level
     *
     * @mbg.generated Mon Feb 20 14:58:54 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_fridge_level
     *
     * @mbg.generated Mon Feb 20 14:58:54 CST 2023
     */
    int insert(LabFridgeLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_fridge_level
     *
     * @mbg.generated Mon Feb 20 14:58:54 CST 2023
     */
    int insertSelective(LabFridgeLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_fridge_level
     *
     * @mbg.generated Mon Feb 20 14:58:54 CST 2023
     */
    LabFridgeLevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_fridge_level
     *
     * @mbg.generated Mon Feb 20 14:58:54 CST 2023
     */
    int updateByPrimaryKeySelective(LabFridgeLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_fridge_level
     *
     * @mbg.generated Mon Feb 20 14:58:54 CST 2023
     */
    int updateByPrimaryKey(LabFridgeLevel record);

    /**
     *
     * 自定义部分
     */
    List<LabFridgeLevel> getSampleTypeByFridgeNoAndLevel(LabFridgeLevel labFridgeLevel);

    List<LabFridgeLevel> getFridgeUsedLevel(String fridgeNo);


}
