package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.NyuenIdV;

import java.util.List;

public interface NyuenIdVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nyuen_id_v
     *
     * @mbg.generated Tue Nov 07 15:47:08 CST 2023
     */
    int insert(NyuenIdV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nyuen_id_v
     *
     * @mbg.generated Tue Nov 07 15:47:08 CST 2023
     */
    int insertSelective(NyuenIdV record);

    /**
     *
     * 自定义部分
     */

    List<String> getAllSnpId();
}
