package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.Reference;

import java.util.List;

public interface ReferenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reference
     *
     * @mbg.generated Tue Nov 22 15:45:42 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reference
     *
     * @mbg.generated Tue Nov 22 15:45:42 CST 2022
     */
    int insert(Reference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reference
     *
     * @mbg.generated Tue Nov 22 15:45:42 CST 2022
     */
    int insertSelective(Reference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reference
     *
     * @mbg.generated Tue Nov 22 15:45:42 CST 2022
     */
    Reference selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reference
     *
     * @mbg.generated Tue Nov 22 15:45:42 CST 2022
     */
    int updateByPrimaryKeySelective(Reference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reference
     *
     * @mbg.generated Tue Nov 22 15:45:42 CST 2022
     */
    int updateByPrimaryKey(Reference record);

    List<Reference> getReferenceByCode(String code);

}
