package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.SampleLabInfo;

public interface SampleLabInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_lab_info
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_lab_info
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    int insert(SampleLabInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_lab_info
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    int insertSelective(SampleLabInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_lab_info
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    SampleLabInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_lab_info
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    int updateByPrimaryKeySelective(SampleLabInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_lab_info
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    int updateByPrimaryKey(SampleLabInfo record);
}