package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.SampleTypeSavePeriod;

public interface SampleTypeSavePeriodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_type_save_period
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_type_save_period
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    int insert(SampleTypeSavePeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_type_save_period
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    int insertSelective(SampleTypeSavePeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_type_save_period
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    SampleTypeSavePeriod selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_type_save_period
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    int updateByPrimaryKeySelective(SampleTypeSavePeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_type_save_period
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    int updateByPrimaryKey(SampleTypeSavePeriod record);

    /**
     *
     * 自定义部分
     */

    Integer getPeriodBySampleType(String sampleType);
}
