package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.SampleSiteRule;

import java.util.List;

public interface SampleSiteRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_site_rule
     *
     * @mbg.generated Mon Nov 21 14:04:32 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_site_rule
     *
     * @mbg.generated Mon Nov 21 14:04:32 CST 2022
     */
    int insert(SampleSiteRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_site_rule
     *
     * @mbg.generated Mon Nov 21 14:04:32 CST 2022
     */
    int insertSelective(SampleSiteRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_site_rule
     *
     * @mbg.generated Mon Nov 21 14:04:32 CST 2022
     */
    SampleSiteRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_site_rule
     *
     * @mbg.generated Mon Nov 21 14:04:32 CST 2022
     */
    int updateByPrimaryKeySelective(SampleSiteRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_site_rule
     *
     * @mbg.generated Mon Nov 21 14:04:32 CST 2022
     */
    int updateByPrimaryKey(SampleSiteRule record);

    /**
     *
     * 自定义部分
     */

    List<SampleSiteRule> getHoleAndAssayByProductName(List<String> productNames);

    List<String> getAllCnvProduct();

}
