package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.SampleSiteRuleV;

import java.util.List;

public interface SampleSiteRuleVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_site_rule_v
     *
     * @mbg.generated Wed Nov 15 13:23:01 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_site_rule_v
     *
     * @mbg.generated Wed Nov 15 13:23:01 CST 2023
     */
    int insert(SampleSiteRuleV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_site_rule_v
     *
     * @mbg.generated Wed Nov 15 13:23:01 CST 2023
     */
    int insertSelective(SampleSiteRuleV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_site_rule_v
     *
     * @mbg.generated Wed Nov 15 13:23:01 CST 2023
     */
    SampleSiteRuleV selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_site_rule_v
     *
     * @mbg.generated Wed Nov 15 13:23:01 CST 2023
     */
    int updateByPrimaryKeySelective(SampleSiteRuleV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_site_rule_v
     *
     * @mbg.generated Wed Nov 15 13:23:01 CST 2023
     */
    int updateByPrimaryKey(SampleSiteRuleV record);

    /**
     *
     * 自定义部分
     */

    List<SampleSiteRuleV> getVHoleByProductName(List<String> productNames);

}
