package com.nyuen.camunda.mapper;

import com.nyuen.camunda.domain.po.SampleStorageOperation;

import java.util.List;

public interface SampleStorageOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_storage_operation
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_storage_operation
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    int insert(SampleStorageOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_storage_operation
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    int insertSelective(SampleStorageOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_storage_operation
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    SampleStorageOperation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_storage_operation
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    int updateByPrimaryKeySelective(SampleStorageOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_storage_operation
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    int updateByPrimaryKey(SampleStorageOperation record);

    /**
     *
     * 自定义部分
     */

    List<SampleStorageOperation> getSampleStorageOperation(String sampleNum);
}
