server:
  port: 8009

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ims_camunda?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

file:
  saveRootPath: D:/test/camunda-file/
  readRootPath: D:/test/camunda-file/

#是否开启swagger
swagger:
  enabled: true

operationLogService: http://report.nyuen-group.com:8200/api-report/oplog/addOperationLog
