server:
  port: 8009

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ims_camunda?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root


