package com.nyuen.camunda.domain.po;

import java.util.Date;

public class ActGeBytearray {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String deploymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.GENERATED_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Byte generated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.CREATE_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String rootProcInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date removalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.BYTES_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private byte[] bytes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.ID_
     *
     * @return the value of act_ge_bytearray.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.ID_
     *
     * @param id the value for act_ge_bytearray.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.REV_
     *
     * @return the value of act_ge_bytearray.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.REV_
     *
     * @param rev the value for act_ge_bytearray.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.NAME_
     *
     * @return the value of act_ge_bytearray.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.NAME_
     *
     * @param name the value for act_ge_bytearray.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @return the value of act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @param deploymentId the value for act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId == null ? null : deploymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.GENERATED_
     *
     * @return the value of act_ge_bytearray.GENERATED_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Byte getGenerated() {
        return generated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.GENERATED_
     *
     * @param generated the value for act_ge_bytearray.GENERATED_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setGenerated(Byte generated) {
        this.generated = generated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.TENANT_ID_
     *
     * @return the value of act_ge_bytearray.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.TENANT_ID_
     *
     * @param tenantId the value for act_ge_bytearray.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.TYPE_
     *
     * @return the value of act_ge_bytearray.TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.TYPE_
     *
     * @param type the value for act_ge_bytearray.TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.CREATE_TIME_
     *
     * @return the value of act_ge_bytearray.CREATE_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.CREATE_TIME_
     *
     * @param createTime the value for act_ge_bytearray.CREATE_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.ROOT_PROC_INST_ID_
     *
     * @return the value of act_ge_bytearray.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getRootProcInstId() {
        return rootProcInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.ROOT_PROC_INST_ID_
     *
     * @param rootProcInstId the value for act_ge_bytearray.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRootProcInstId(String rootProcInstId) {
        this.rootProcInstId = rootProcInstId == null ? null : rootProcInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.REMOVAL_TIME_
     *
     * @return the value of act_ge_bytearray.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getRemovalTime() {
        return removalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.REMOVAL_TIME_
     *
     * @param removalTime the value for act_ge_bytearray.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRemovalTime(Date removalTime) {
        this.removalTime = removalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.BYTES_
     *
     * @return the value of act_ge_bytearray.BYTES_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public byte[] getBytes() {
        return bytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.BYTES_
     *
     * @param bytes the value for act_ge_bytearray.BYTES_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }
}