package com.nyuen.camunda.domain.po;

import java.util.Date;

public class ActHiIdentitylink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.TIMESTAMP_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.USER_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.GROUP_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String rootProcInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.OPERATION_TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String operationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.ASSIGNER_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String assignerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procDefKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date removalTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.ID_
     *
     * @return the value of act_hi_identitylink.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.ID_
     *
     * @param id the value for act_hi_identitylink.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.TIMESTAMP_
     *
     * @return the value of act_hi_identitylink.TIMESTAMP_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.TIMESTAMP_
     *
     * @param timestamp the value for act_hi_identitylink.TIMESTAMP_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.TYPE_
     *
     * @return the value of act_hi_identitylink.TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.TYPE_
     *
     * @param type the value for act_hi_identitylink.TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.USER_ID_
     *
     * @return the value of act_hi_identitylink.USER_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.USER_ID_
     *
     * @param userId the value for act_hi_identitylink.USER_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.GROUP_ID_
     *
     * @return the value of act_hi_identitylink.GROUP_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.GROUP_ID_
     *
     * @param groupId the value for act_hi_identitylink.GROUP_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.TASK_ID_
     *
     * @return the value of act_hi_identitylink.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.TASK_ID_
     *
     * @param taskId the value for act_hi_identitylink.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.ROOT_PROC_INST_ID_
     *
     * @return the value of act_hi_identitylink.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getRootProcInstId() {
        return rootProcInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.ROOT_PROC_INST_ID_
     *
     * @param rootProcInstId the value for act_hi_identitylink.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRootProcInstId(String rootProcInstId) {
        this.rootProcInstId = rootProcInstId == null ? null : rootProcInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.PROC_DEF_ID_
     *
     * @return the value of act_hi_identitylink.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.PROC_DEF_ID_
     *
     * @param procDefId the value for act_hi_identitylink.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.OPERATION_TYPE_
     *
     * @return the value of act_hi_identitylink.OPERATION_TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.OPERATION_TYPE_
     *
     * @param operationType the value for act_hi_identitylink.OPERATION_TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.ASSIGNER_ID_
     *
     * @return the value of act_hi_identitylink.ASSIGNER_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getAssignerId() {
        return assignerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.ASSIGNER_ID_
     *
     * @param assignerId the value for act_hi_identitylink.ASSIGNER_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setAssignerId(String assignerId) {
        this.assignerId = assignerId == null ? null : assignerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.PROC_DEF_KEY_
     *
     * @return the value of act_hi_identitylink.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcDefKey() {
        return procDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.PROC_DEF_KEY_
     *
     * @param procDefKey the value for act_hi_identitylink.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcDefKey(String procDefKey) {
        this.procDefKey = procDefKey == null ? null : procDefKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.TENANT_ID_
     *
     * @return the value of act_hi_identitylink.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.TENANT_ID_
     *
     * @param tenantId the value for act_hi_identitylink.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.REMOVAL_TIME_
     *
     * @return the value of act_hi_identitylink.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getRemovalTime() {
        return removalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.REMOVAL_TIME_
     *
     * @param removalTime the value for act_hi_identitylink.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRemovalTime(Date removalTime) {
        this.removalTime = removalTime;
    }
}