package com.nyuen.camunda.domain.po;

import java.util.Date;

public class ActHiComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_comment.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_comment.TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_comment.TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_comment.USER_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_comment.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_comment.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String rootProcInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_comment.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_comment.ACTION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_comment.MESSAGE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_comment.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_comment.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date removalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_comment.FULL_MSG_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private byte[] fullMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_comment.ID_
     *
     * @return the value of act_hi_comment.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_comment.ID_
     *
     * @param id the value for act_hi_comment.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_comment.TYPE_
     *
     * @return the value of act_hi_comment.TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_comment.TYPE_
     *
     * @param type the value for act_hi_comment.TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_comment.TIME_
     *
     * @return the value of act_hi_comment.TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_comment.TIME_
     *
     * @param time the value for act_hi_comment.TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_comment.USER_ID_
     *
     * @return the value of act_hi_comment.USER_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_comment.USER_ID_
     *
     * @param userId the value for act_hi_comment.USER_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_comment.TASK_ID_
     *
     * @return the value of act_hi_comment.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_comment.TASK_ID_
     *
     * @param taskId the value for act_hi_comment.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_comment.ROOT_PROC_INST_ID_
     *
     * @return the value of act_hi_comment.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getRootProcInstId() {
        return rootProcInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_comment.ROOT_PROC_INST_ID_
     *
     * @param rootProcInstId the value for act_hi_comment.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRootProcInstId(String rootProcInstId) {
        this.rootProcInstId = rootProcInstId == null ? null : rootProcInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_comment.PROC_INST_ID_
     *
     * @return the value of act_hi_comment.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_comment.PROC_INST_ID_
     *
     * @param procInstId the value for act_hi_comment.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_comment.ACTION_
     *
     * @return the value of act_hi_comment.ACTION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_comment.ACTION_
     *
     * @param action the value for act_hi_comment.ACTION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_comment.MESSAGE_
     *
     * @return the value of act_hi_comment.MESSAGE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_comment.MESSAGE_
     *
     * @param message the value for act_hi_comment.MESSAGE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_comment.TENANT_ID_
     *
     * @return the value of act_hi_comment.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_comment.TENANT_ID_
     *
     * @param tenantId the value for act_hi_comment.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_comment.REMOVAL_TIME_
     *
     * @return the value of act_hi_comment.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getRemovalTime() {
        return removalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_comment.REMOVAL_TIME_
     *
     * @param removalTime the value for act_hi_comment.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRemovalTime(Date removalTime) {
        this.removalTime = removalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_comment.FULL_MSG_
     *
     * @return the value of act_hi_comment.FULL_MSG_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public byte[] getFullMsg() {
        return fullMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_comment.FULL_MSG_
     *
     * @param fullMsg the value for act_hi_comment.FULL_MSG_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setFullMsg(byte[] fullMsg) {
        this.fullMsg = fullMsg;
    }
}