package com.nyuen.camunda.domain.po;

import java.util.Date;

public class ActHiActinst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.PARENT_ACT_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String parentActInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procDefKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String rootProcInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.ACT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String actId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.CALL_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String callProcInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.CALL_CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String callCaseInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.ACT_NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String actName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.ACT_TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String actType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.ASSIGNEE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String assignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.START_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.END_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.DURATION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Long duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.ACT_INST_STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer actInstState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.SEQUENCE_COUNTER_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Long sequenceCounter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_actinst.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date removalTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.ID_
     *
     * @return the value of act_hi_actinst.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.ID_
     *
     * @param id the value for act_hi_actinst.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.PARENT_ACT_INST_ID_
     *
     * @return the value of act_hi_actinst.PARENT_ACT_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getParentActInstId() {
        return parentActInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.PARENT_ACT_INST_ID_
     *
     * @param parentActInstId the value for act_hi_actinst.PARENT_ACT_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setParentActInstId(String parentActInstId) {
        this.parentActInstId = parentActInstId == null ? null : parentActInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.PROC_DEF_KEY_
     *
     * @return the value of act_hi_actinst.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcDefKey() {
        return procDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.PROC_DEF_KEY_
     *
     * @param procDefKey the value for act_hi_actinst.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcDefKey(String procDefKey) {
        this.procDefKey = procDefKey == null ? null : procDefKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.PROC_DEF_ID_
     *
     * @return the value of act_hi_actinst.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.PROC_DEF_ID_
     *
     * @param procDefId the value for act_hi_actinst.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.ROOT_PROC_INST_ID_
     *
     * @return the value of act_hi_actinst.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getRootProcInstId() {
        return rootProcInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.ROOT_PROC_INST_ID_
     *
     * @param rootProcInstId the value for act_hi_actinst.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRootProcInstId(String rootProcInstId) {
        this.rootProcInstId = rootProcInstId == null ? null : rootProcInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.PROC_INST_ID_
     *
     * @return the value of act_hi_actinst.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.PROC_INST_ID_
     *
     * @param procInstId the value for act_hi_actinst.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.EXECUTION_ID_
     *
     * @return the value of act_hi_actinst.EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.EXECUTION_ID_
     *
     * @param executionId the value for act_hi_actinst.EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.ACT_ID_
     *
     * @return the value of act_hi_actinst.ACT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.ACT_ID_
     *
     * @param actId the value for act_hi_actinst.ACT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setActId(String actId) {
        this.actId = actId == null ? null : actId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.TASK_ID_
     *
     * @return the value of act_hi_actinst.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.TASK_ID_
     *
     * @param taskId the value for act_hi_actinst.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.CALL_PROC_INST_ID_
     *
     * @return the value of act_hi_actinst.CALL_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCallProcInstId() {
        return callProcInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.CALL_PROC_INST_ID_
     *
     * @param callProcInstId the value for act_hi_actinst.CALL_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCallProcInstId(String callProcInstId) {
        this.callProcInstId = callProcInstId == null ? null : callProcInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.CALL_CASE_INST_ID_
     *
     * @return the value of act_hi_actinst.CALL_CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCallCaseInstId() {
        return callCaseInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.CALL_CASE_INST_ID_
     *
     * @param callCaseInstId the value for act_hi_actinst.CALL_CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCallCaseInstId(String callCaseInstId) {
        this.callCaseInstId = callCaseInstId == null ? null : callCaseInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.ACT_NAME_
     *
     * @return the value of act_hi_actinst.ACT_NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getActName() {
        return actName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.ACT_NAME_
     *
     * @param actName the value for act_hi_actinst.ACT_NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setActName(String actName) {
        this.actName = actName == null ? null : actName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.ACT_TYPE_
     *
     * @return the value of act_hi_actinst.ACT_TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getActType() {
        return actType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.ACT_TYPE_
     *
     * @param actType the value for act_hi_actinst.ACT_TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setActType(String actType) {
        this.actType = actType == null ? null : actType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.ASSIGNEE_
     *
     * @return the value of act_hi_actinst.ASSIGNEE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getAssignee() {
        return assignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.ASSIGNEE_
     *
     * @param assignee the value for act_hi_actinst.ASSIGNEE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee == null ? null : assignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.START_TIME_
     *
     * @return the value of act_hi_actinst.START_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.START_TIME_
     *
     * @param startTime the value for act_hi_actinst.START_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.END_TIME_
     *
     * @return the value of act_hi_actinst.END_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.END_TIME_
     *
     * @param endTime the value for act_hi_actinst.END_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.DURATION_
     *
     * @return the value of act_hi_actinst.DURATION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.DURATION_
     *
     * @param duration the value for act_hi_actinst.DURATION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.ACT_INST_STATE_
     *
     * @return the value of act_hi_actinst.ACT_INST_STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getActInstState() {
        return actInstState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.ACT_INST_STATE_
     *
     * @param actInstState the value for act_hi_actinst.ACT_INST_STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setActInstState(Integer actInstState) {
        this.actInstState = actInstState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.SEQUENCE_COUNTER_
     *
     * @return the value of act_hi_actinst.SEQUENCE_COUNTER_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Long getSequenceCounter() {
        return sequenceCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.SEQUENCE_COUNTER_
     *
     * @param sequenceCounter the value for act_hi_actinst.SEQUENCE_COUNTER_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setSequenceCounter(Long sequenceCounter) {
        this.sequenceCounter = sequenceCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.TENANT_ID_
     *
     * @return the value of act_hi_actinst.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.TENANT_ID_
     *
     * @param tenantId the value for act_hi_actinst.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_actinst.REMOVAL_TIME_
     *
     * @return the value of act_hi_actinst.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getRemovalTime() {
        return removalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_actinst.REMOVAL_TIME_
     *
     * @param removalTime the value for act_hi_actinst.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRemovalTime(Date removalTime) {
        this.removalTime = removalTime;
    }
}