package com.nyuen.camunda.domain.po;

import java.util.Date;

public class ActHiVarinst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procDefKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String rootProcInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.ACT_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String actInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.CASE_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String caseDefKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.CASE_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String caseDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String caseInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.CASE_EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String caseExecutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.VAR_TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String varType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.CREATE_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.BYTEARRAY_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String bytearrayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.DOUBLE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Double double_;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.LONG_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Long long_;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.TEXT_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.TEXT2_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String text2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date removalTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.ID_
     *
     * @return the value of act_hi_varinst.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.ID_
     *
     * @param id the value for act_hi_varinst.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.PROC_DEF_KEY_
     *
     * @return the value of act_hi_varinst.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcDefKey() {
        return procDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.PROC_DEF_KEY_
     *
     * @param procDefKey the value for act_hi_varinst.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcDefKey(String procDefKey) {
        this.procDefKey = procDefKey == null ? null : procDefKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.PROC_DEF_ID_
     *
     * @return the value of act_hi_varinst.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.PROC_DEF_ID_
     *
     * @param procDefId the value for act_hi_varinst.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.ROOT_PROC_INST_ID_
     *
     * @return the value of act_hi_varinst.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getRootProcInstId() {
        return rootProcInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.ROOT_PROC_INST_ID_
     *
     * @param rootProcInstId the value for act_hi_varinst.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRootProcInstId(String rootProcInstId) {
        this.rootProcInstId = rootProcInstId == null ? null : rootProcInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.PROC_INST_ID_
     *
     * @return the value of act_hi_varinst.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.PROC_INST_ID_
     *
     * @param procInstId the value for act_hi_varinst.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.EXECUTION_ID_
     *
     * @return the value of act_hi_varinst.EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.EXECUTION_ID_
     *
     * @param executionId the value for act_hi_varinst.EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.ACT_INST_ID_
     *
     * @return the value of act_hi_varinst.ACT_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getActInstId() {
        return actInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.ACT_INST_ID_
     *
     * @param actInstId the value for act_hi_varinst.ACT_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setActInstId(String actInstId) {
        this.actInstId = actInstId == null ? null : actInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.CASE_DEF_KEY_
     *
     * @return the value of act_hi_varinst.CASE_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCaseDefKey() {
        return caseDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.CASE_DEF_KEY_
     *
     * @param caseDefKey the value for act_hi_varinst.CASE_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCaseDefKey(String caseDefKey) {
        this.caseDefKey = caseDefKey == null ? null : caseDefKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.CASE_DEF_ID_
     *
     * @return the value of act_hi_varinst.CASE_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCaseDefId() {
        return caseDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.CASE_DEF_ID_
     *
     * @param caseDefId the value for act_hi_varinst.CASE_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCaseDefId(String caseDefId) {
        this.caseDefId = caseDefId == null ? null : caseDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.CASE_INST_ID_
     *
     * @return the value of act_hi_varinst.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCaseInstId() {
        return caseInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.CASE_INST_ID_
     *
     * @param caseInstId the value for act_hi_varinst.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCaseInstId(String caseInstId) {
        this.caseInstId = caseInstId == null ? null : caseInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.CASE_EXECUTION_ID_
     *
     * @return the value of act_hi_varinst.CASE_EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCaseExecutionId() {
        return caseExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.CASE_EXECUTION_ID_
     *
     * @param caseExecutionId the value for act_hi_varinst.CASE_EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCaseExecutionId(String caseExecutionId) {
        this.caseExecutionId = caseExecutionId == null ? null : caseExecutionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.TASK_ID_
     *
     * @return the value of act_hi_varinst.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.TASK_ID_
     *
     * @param taskId the value for act_hi_varinst.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.NAME_
     *
     * @return the value of act_hi_varinst.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.NAME_
     *
     * @param name the value for act_hi_varinst.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.VAR_TYPE_
     *
     * @return the value of act_hi_varinst.VAR_TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getVarType() {
        return varType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.VAR_TYPE_
     *
     * @param varType the value for act_hi_varinst.VAR_TYPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setVarType(String varType) {
        this.varType = varType == null ? null : varType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.CREATE_TIME_
     *
     * @return the value of act_hi_varinst.CREATE_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.CREATE_TIME_
     *
     * @param createTime the value for act_hi_varinst.CREATE_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.REV_
     *
     * @return the value of act_hi_varinst.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.REV_
     *
     * @param rev the value for act_hi_varinst.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.BYTEARRAY_ID_
     *
     * @return the value of act_hi_varinst.BYTEARRAY_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getBytearrayId() {
        return bytearrayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.BYTEARRAY_ID_
     *
     * @param bytearrayId the value for act_hi_varinst.BYTEARRAY_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setBytearrayId(String bytearrayId) {
        this.bytearrayId = bytearrayId == null ? null : bytearrayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.DOUBLE_
     *
     * @return the value of act_hi_varinst.DOUBLE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Double getDouble_() {
        return double_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.DOUBLE_
     *
     * @param double_ the value for act_hi_varinst.DOUBLE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setDouble(Double double_) {
        this.double_ = double_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.LONG_
     *
     * @return the value of act_hi_varinst.LONG_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Long getLong_() {
        return long_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.LONG_
     *
     * @param long_ the value for act_hi_varinst.LONG_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setLong(Long long_) {
        this.long_ = long_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.TEXT_
     *
     * @return the value of act_hi_varinst.TEXT_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.TEXT_
     *
     * @param text the value for act_hi_varinst.TEXT_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.TEXT2_
     *
     * @return the value of act_hi_varinst.TEXT2_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.TEXT2_
     *
     * @param text2 the value for act_hi_varinst.TEXT2_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.TENANT_ID_
     *
     * @return the value of act_hi_varinst.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.TENANT_ID_
     *
     * @param tenantId the value for act_hi_varinst.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.STATE_
     *
     * @return the value of act_hi_varinst.STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.STATE_
     *
     * @param state the value for act_hi_varinst.STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.REMOVAL_TIME_
     *
     * @return the value of act_hi_varinst.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getRemovalTime() {
        return removalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.REMOVAL_TIME_
     *
     * @param removalTime the value for act_hi_varinst.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRemovalTime(Date removalTime) {
        this.removalTime = removalTime;
    }
}
