package com.nyuen.camunda.domain.po;

import java.util.Date;

public class ActHiTaskinst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.TASK_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String taskDefKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procDefKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String rootProcInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.CASE_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String caseDefKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.CASE_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String caseDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String caseInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.CASE_EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String caseExecutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.ACT_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String actInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.PARENT_TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String parentTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.DESCRIPTION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.OWNER_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.ASSIGNEE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String assignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.START_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.END_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.DURATION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Long duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.DELETE_REASON_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String deleteReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.PRIORITY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.DUE_DATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.FOLLOW_UP_DATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date followUpDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date removalTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.ID_
     *
     * @return the value of act_hi_taskinst.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.ID_
     *
     * @param id the value for act_hi_taskinst.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.TASK_DEF_KEY_
     *
     * @return the value of act_hi_taskinst.TASK_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTaskDefKey() {
        return taskDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.TASK_DEF_KEY_
     *
     * @param taskDefKey the value for act_hi_taskinst.TASK_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTaskDefKey(String taskDefKey) {
        this.taskDefKey = taskDefKey == null ? null : taskDefKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.PROC_DEF_KEY_
     *
     * @return the value of act_hi_taskinst.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcDefKey() {
        return procDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.PROC_DEF_KEY_
     *
     * @param procDefKey the value for act_hi_taskinst.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcDefKey(String procDefKey) {
        this.procDefKey = procDefKey == null ? null : procDefKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.PROC_DEF_ID_
     *
     * @return the value of act_hi_taskinst.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.PROC_DEF_ID_
     *
     * @param procDefId the value for act_hi_taskinst.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.ROOT_PROC_INST_ID_
     *
     * @return the value of act_hi_taskinst.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getRootProcInstId() {
        return rootProcInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.ROOT_PROC_INST_ID_
     *
     * @param rootProcInstId the value for act_hi_taskinst.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRootProcInstId(String rootProcInstId) {
        this.rootProcInstId = rootProcInstId == null ? null : rootProcInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.PROC_INST_ID_
     *
     * @return the value of act_hi_taskinst.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.PROC_INST_ID_
     *
     * @param procInstId the value for act_hi_taskinst.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.EXECUTION_ID_
     *
     * @return the value of act_hi_taskinst.EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.EXECUTION_ID_
     *
     * @param executionId the value for act_hi_taskinst.EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.CASE_DEF_KEY_
     *
     * @return the value of act_hi_taskinst.CASE_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCaseDefKey() {
        return caseDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.CASE_DEF_KEY_
     *
     * @param caseDefKey the value for act_hi_taskinst.CASE_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCaseDefKey(String caseDefKey) {
        this.caseDefKey = caseDefKey == null ? null : caseDefKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.CASE_DEF_ID_
     *
     * @return the value of act_hi_taskinst.CASE_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCaseDefId() {
        return caseDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.CASE_DEF_ID_
     *
     * @param caseDefId the value for act_hi_taskinst.CASE_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCaseDefId(String caseDefId) {
        this.caseDefId = caseDefId == null ? null : caseDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.CASE_INST_ID_
     *
     * @return the value of act_hi_taskinst.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCaseInstId() {
        return caseInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.CASE_INST_ID_
     *
     * @param caseInstId the value for act_hi_taskinst.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCaseInstId(String caseInstId) {
        this.caseInstId = caseInstId == null ? null : caseInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.CASE_EXECUTION_ID_
     *
     * @return the value of act_hi_taskinst.CASE_EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCaseExecutionId() {
        return caseExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.CASE_EXECUTION_ID_
     *
     * @param caseExecutionId the value for act_hi_taskinst.CASE_EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCaseExecutionId(String caseExecutionId) {
        this.caseExecutionId = caseExecutionId == null ? null : caseExecutionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.ACT_INST_ID_
     *
     * @return the value of act_hi_taskinst.ACT_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getActInstId() {
        return actInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.ACT_INST_ID_
     *
     * @param actInstId the value for act_hi_taskinst.ACT_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setActInstId(String actInstId) {
        this.actInstId = actInstId == null ? null : actInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.NAME_
     *
     * @return the value of act_hi_taskinst.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.NAME_
     *
     * @param name the value for act_hi_taskinst.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.PARENT_TASK_ID_
     *
     * @return the value of act_hi_taskinst.PARENT_TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getParentTaskId() {
        return parentTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.PARENT_TASK_ID_
     *
     * @param parentTaskId the value for act_hi_taskinst.PARENT_TASK_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setParentTaskId(String parentTaskId) {
        this.parentTaskId = parentTaskId == null ? null : parentTaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.DESCRIPTION_
     *
     * @return the value of act_hi_taskinst.DESCRIPTION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.DESCRIPTION_
     *
     * @param description the value for act_hi_taskinst.DESCRIPTION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.OWNER_
     *
     * @return the value of act_hi_taskinst.OWNER_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.OWNER_
     *
     * @param owner the value for act_hi_taskinst.OWNER_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.ASSIGNEE_
     *
     * @return the value of act_hi_taskinst.ASSIGNEE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getAssignee() {
        return assignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.ASSIGNEE_
     *
     * @param assignee the value for act_hi_taskinst.ASSIGNEE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee == null ? null : assignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.START_TIME_
     *
     * @return the value of act_hi_taskinst.START_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.START_TIME_
     *
     * @param startTime the value for act_hi_taskinst.START_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.END_TIME_
     *
     * @return the value of act_hi_taskinst.END_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.END_TIME_
     *
     * @param endTime the value for act_hi_taskinst.END_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.DURATION_
     *
     * @return the value of act_hi_taskinst.DURATION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.DURATION_
     *
     * @param duration the value for act_hi_taskinst.DURATION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.DELETE_REASON_
     *
     * @return the value of act_hi_taskinst.DELETE_REASON_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getDeleteReason() {
        return deleteReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.DELETE_REASON_
     *
     * @param deleteReason the value for act_hi_taskinst.DELETE_REASON_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setDeleteReason(String deleteReason) {
        this.deleteReason = deleteReason == null ? null : deleteReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.PRIORITY_
     *
     * @return the value of act_hi_taskinst.PRIORITY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.PRIORITY_
     *
     * @param priority the value for act_hi_taskinst.PRIORITY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.DUE_DATE_
     *
     * @return the value of act_hi_taskinst.DUE_DATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.DUE_DATE_
     *
     * @param dueDate the value for act_hi_taskinst.DUE_DATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.FOLLOW_UP_DATE_
     *
     * @return the value of act_hi_taskinst.FOLLOW_UP_DATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getFollowUpDate() {
        return followUpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.FOLLOW_UP_DATE_
     *
     * @param followUpDate the value for act_hi_taskinst.FOLLOW_UP_DATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setFollowUpDate(Date followUpDate) {
        this.followUpDate = followUpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.TENANT_ID_
     *
     * @return the value of act_hi_taskinst.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.TENANT_ID_
     *
     * @param tenantId the value for act_hi_taskinst.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.REMOVAL_TIME_
     *
     * @return the value of act_hi_taskinst.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getRemovalTime() {
        return removalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.REMOVAL_TIME_
     *
     * @param removalTime the value for act_hi_taskinst.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRemovalTime(Date removalTime) {
        this.removalTime = removalTime;
    }
}