package com.nyuen.camunda.domain.po;

import java.util.Date;

public class ActHiProcinst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.BUSINESS_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String businessKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procDefKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.START_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.END_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Date removalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.DURATION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Long duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.START_USER_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String startUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.START_ACT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String startActId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.END_ACT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String endActId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.SUPER_PROCESS_INSTANCE_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String superProcessInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String rootProcInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.SUPER_CASE_INSTANCE_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String superCaseInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String caseInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.DELETE_REASON_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String deleteReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.ID_
     *
     * @return the value of act_hi_procinst.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.ID_
     *
     * @param id the value for act_hi_procinst.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.PROC_INST_ID_
     *
     * @return the value of act_hi_procinst.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.PROC_INST_ID_
     *
     * @param procInstId the value for act_hi_procinst.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.BUSINESS_KEY_
     *
     * @return the value of act_hi_procinst.BUSINESS_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getBusinessKey() {
        return businessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.BUSINESS_KEY_
     *
     * @param businessKey the value for act_hi_procinst.BUSINESS_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey == null ? null : businessKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.PROC_DEF_KEY_
     *
     * @return the value of act_hi_procinst.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcDefKey() {
        return procDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.PROC_DEF_KEY_
     *
     * @param procDefKey the value for act_hi_procinst.PROC_DEF_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcDefKey(String procDefKey) {
        this.procDefKey = procDefKey == null ? null : procDefKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.PROC_DEF_ID_
     *
     * @return the value of act_hi_procinst.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.PROC_DEF_ID_
     *
     * @param procDefId the value for act_hi_procinst.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.START_TIME_
     *
     * @return the value of act_hi_procinst.START_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.START_TIME_
     *
     * @param startTime the value for act_hi_procinst.START_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.END_TIME_
     *
     * @return the value of act_hi_procinst.END_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.END_TIME_
     *
     * @param endTime the value for act_hi_procinst.END_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.REMOVAL_TIME_
     *
     * @return the value of act_hi_procinst.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Date getRemovalTime() {
        return removalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.REMOVAL_TIME_
     *
     * @param removalTime the value for act_hi_procinst.REMOVAL_TIME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRemovalTime(Date removalTime) {
        this.removalTime = removalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.DURATION_
     *
     * @return the value of act_hi_procinst.DURATION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.DURATION_
     *
     * @param duration the value for act_hi_procinst.DURATION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.START_USER_ID_
     *
     * @return the value of act_hi_procinst.START_USER_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getStartUserId() {
        return startUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.START_USER_ID_
     *
     * @param startUserId the value for act_hi_procinst.START_USER_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setStartUserId(String startUserId) {
        this.startUserId = startUserId == null ? null : startUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.START_ACT_ID_
     *
     * @return the value of act_hi_procinst.START_ACT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getStartActId() {
        return startActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.START_ACT_ID_
     *
     * @param startActId the value for act_hi_procinst.START_ACT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setStartActId(String startActId) {
        this.startActId = startActId == null ? null : startActId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.END_ACT_ID_
     *
     * @return the value of act_hi_procinst.END_ACT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getEndActId() {
        return endActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.END_ACT_ID_
     *
     * @param endActId the value for act_hi_procinst.END_ACT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setEndActId(String endActId) {
        this.endActId = endActId == null ? null : endActId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.SUPER_PROCESS_INSTANCE_ID_
     *
     * @return the value of act_hi_procinst.SUPER_PROCESS_INSTANCE_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getSuperProcessInstanceId() {
        return superProcessInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.SUPER_PROCESS_INSTANCE_ID_
     *
     * @param superProcessInstanceId the value for act_hi_procinst.SUPER_PROCESS_INSTANCE_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setSuperProcessInstanceId(String superProcessInstanceId) {
        this.superProcessInstanceId = superProcessInstanceId == null ? null : superProcessInstanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.ROOT_PROC_INST_ID_
     *
     * @return the value of act_hi_procinst.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getRootProcInstId() {
        return rootProcInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.ROOT_PROC_INST_ID_
     *
     * @param rootProcInstId the value for act_hi_procinst.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRootProcInstId(String rootProcInstId) {
        this.rootProcInstId = rootProcInstId == null ? null : rootProcInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.SUPER_CASE_INSTANCE_ID_
     *
     * @return the value of act_hi_procinst.SUPER_CASE_INSTANCE_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getSuperCaseInstanceId() {
        return superCaseInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.SUPER_CASE_INSTANCE_ID_
     *
     * @param superCaseInstanceId the value for act_hi_procinst.SUPER_CASE_INSTANCE_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setSuperCaseInstanceId(String superCaseInstanceId) {
        this.superCaseInstanceId = superCaseInstanceId == null ? null : superCaseInstanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.CASE_INST_ID_
     *
     * @return the value of act_hi_procinst.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCaseInstId() {
        return caseInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.CASE_INST_ID_
     *
     * @param caseInstId the value for act_hi_procinst.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCaseInstId(String caseInstId) {
        this.caseInstId = caseInstId == null ? null : caseInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.DELETE_REASON_
     *
     * @return the value of act_hi_procinst.DELETE_REASON_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getDeleteReason() {
        return deleteReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.DELETE_REASON_
     *
     * @param deleteReason the value for act_hi_procinst.DELETE_REASON_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setDeleteReason(String deleteReason) {
        this.deleteReason = deleteReason == null ? null : deleteReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.TENANT_ID_
     *
     * @return the value of act_hi_procinst.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.TENANT_ID_
     *
     * @param tenantId the value for act_hi_procinst.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.STATE_
     *
     * @return the value of act_hi_procinst.STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.STATE_
     *
     * @param state the value for act_hi_procinst.STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}