package com.nyuen.camunda.domain.po;

public class ActIdTenant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_tenant.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_tenant.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_tenant.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_tenant.ID_
     *
     * @return the value of act_id_tenant.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_tenant.ID_
     *
     * @param id the value for act_id_tenant.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_tenant.REV_
     *
     * @return the value of act_id_tenant.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_tenant.REV_
     *
     * @param rev the value for act_id_tenant.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_tenant.NAME_
     *
     * @return the value of act_id_tenant.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_tenant.NAME_
     *
     * @param name the value for act_id_tenant.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}