package com.nyuen.camunda.domain.po;

public class ActRuVariable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.REV_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.TYPE_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.NAME_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.CASE_EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String caseExecutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String caseInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.BATCH_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.BYTEARRAY_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String bytearrayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.DOUBLE_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private Double double_;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.LONG_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private Long long_;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.TEXT_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.TEXT2_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String text2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.VAR_SCOPE_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String varScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.SEQUENCE_COUNTER_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private Long sequenceCounter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.IS_CONCURRENT_LOCAL_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private Byte isConcurrentLocal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_variable.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.ID_
     *
     * @return the value of act_ru_variable.ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.ID_
     *
     * @param id the value for act_ru_variable.ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.REV_
     *
     * @return the value of act_ru_variable.REV_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.REV_
     *
     * @param rev the value for act_ru_variable.REV_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.TYPE_
     *
     * @return the value of act_ru_variable.TYPE_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.TYPE_
     *
     * @param type the value for act_ru_variable.TYPE_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.NAME_
     *
     * @return the value of act_ru_variable.NAME_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.NAME_
     *
     * @param name the value for act_ru_variable.NAME_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.EXECUTION_ID_
     *
     * @return the value of act_ru_variable.EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.EXECUTION_ID_
     *
     * @param executionId the value for act_ru_variable.EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.PROC_INST_ID_
     *
     * @return the value of act_ru_variable.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.PROC_INST_ID_
     *
     * @param procInstId the value for act_ru_variable.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.PROC_DEF_ID_
     *
     * @return the value of act_ru_variable.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.PROC_DEF_ID_
     *
     * @param procDefId the value for act_ru_variable.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.CASE_EXECUTION_ID_
     *
     * @return the value of act_ru_variable.CASE_EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getCaseExecutionId() {
        return caseExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.CASE_EXECUTION_ID_
     *
     * @param caseExecutionId the value for act_ru_variable.CASE_EXECUTION_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setCaseExecutionId(String caseExecutionId) {
        this.caseExecutionId = caseExecutionId == null ? null : caseExecutionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.CASE_INST_ID_
     *
     * @return the value of act_ru_variable.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getCaseInstId() {
        return caseInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.CASE_INST_ID_
     *
     * @param caseInstId the value for act_ru_variable.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setCaseInstId(String caseInstId) {
        this.caseInstId = caseInstId == null ? null : caseInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.TASK_ID_
     *
     * @return the value of act_ru_variable.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.TASK_ID_
     *
     * @param taskId the value for act_ru_variable.TASK_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.BATCH_ID_
     *
     * @return the value of act_ru_variable.BATCH_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.BATCH_ID_
     *
     * @param batchId the value for act_ru_variable.BATCH_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.BYTEARRAY_ID_
     *
     * @return the value of act_ru_variable.BYTEARRAY_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getBytearrayId() {
        return bytearrayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.BYTEARRAY_ID_
     *
     * @param bytearrayId the value for act_ru_variable.BYTEARRAY_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setBytearrayId(String bytearrayId) {
        this.bytearrayId = bytearrayId == null ? null : bytearrayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.DOUBLE_
     *
     * @return the value of act_ru_variable.DOUBLE_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public Double getDouble_() {
        return double_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.DOUBLE_
     *
     * @param double_ the value for act_ru_variable.DOUBLE_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setDouble(Double double_) {
        this.double_ = double_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.LONG_
     *
     * @return the value of act_ru_variable.LONG_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public Long getLong_() {
        return long_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.LONG_
     *
     * @param long_ the value for act_ru_variable.LONG_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setLong(Long long_) {
        this.long_ = long_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.TEXT_
     *
     * @return the value of act_ru_variable.TEXT_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.TEXT_
     *
     * @param text the value for act_ru_variable.TEXT_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.TEXT2_
     *
     * @return the value of act_ru_variable.TEXT2_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.TEXT2_
     *
     * @param text2 the value for act_ru_variable.TEXT2_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.VAR_SCOPE_
     *
     * @return the value of act_ru_variable.VAR_SCOPE_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getVarScope() {
        return varScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.VAR_SCOPE_
     *
     * @param varScope the value for act_ru_variable.VAR_SCOPE_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setVarScope(String varScope) {
        this.varScope = varScope == null ? null : varScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.SEQUENCE_COUNTER_
     *
     * @return the value of act_ru_variable.SEQUENCE_COUNTER_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public Long getSequenceCounter() {
        return sequenceCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.SEQUENCE_COUNTER_
     *
     * @param sequenceCounter the value for act_ru_variable.SEQUENCE_COUNTER_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setSequenceCounter(Long sequenceCounter) {
        this.sequenceCounter = sequenceCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.IS_CONCURRENT_LOCAL_
     *
     * @return the value of act_ru_variable.IS_CONCURRENT_LOCAL_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public Byte getIsConcurrentLocal() {
        return isConcurrentLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.IS_CONCURRENT_LOCAL_
     *
     * @param isConcurrentLocal the value for act_ru_variable.IS_CONCURRENT_LOCAL_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setIsConcurrentLocal(Byte isConcurrentLocal) {
        this.isConcurrentLocal = isConcurrentLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_variable.TENANT_ID_
     *
     * @return the value of act_ru_variable.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_variable.TENANT_ID_
     *
     * @param tenantId the value for act_ru_variable.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 11:07:10 CST 2022
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }
}
