package com.nyuen.camunda.domain.po;

public class ActReCamformdef {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_camformdef.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_camformdef.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_camformdef.KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_camformdef.VERSION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_camformdef.DEPLOYMENT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String deploymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_camformdef.RESOURCE_NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_camformdef.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_camformdef.ID_
     *
     * @return the value of act_re_camformdef.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_camformdef.ID_
     *
     * @param id the value for act_re_camformdef.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_camformdef.REV_
     *
     * @return the value of act_re_camformdef.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_camformdef.REV_
     *
     * @param rev the value for act_re_camformdef.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_camformdef.KEY_
     *
     * @return the value of act_re_camformdef.KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_camformdef.KEY_
     *
     * @param key the value for act_re_camformdef.KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_camformdef.VERSION_
     *
     * @return the value of act_re_camformdef.VERSION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_camformdef.VERSION_
     *
     * @param version the value for act_re_camformdef.VERSION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_camformdef.DEPLOYMENT_ID_
     *
     * @return the value of act_re_camformdef.DEPLOYMENT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_camformdef.DEPLOYMENT_ID_
     *
     * @param deploymentId the value for act_re_camformdef.DEPLOYMENT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId == null ? null : deploymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_camformdef.RESOURCE_NAME_
     *
     * @return the value of act_re_camformdef.RESOURCE_NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_camformdef.RESOURCE_NAME_
     *
     * @param resourceName the value for act_re_camformdef.RESOURCE_NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_camformdef.TENANT_ID_
     *
     * @return the value of act_re_camformdef.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_camformdef.TENANT_ID_
     *
     * @param tenantId the value for act_re_camformdef.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }
}