package com.nyuen.camunda.domain.po;

public class ActReProcdef {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.CATEGORY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.VERSION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.DEPLOYMENT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String deploymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.RESOURCE_NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String dgrmResourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.HAS_START_FORM_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Byte hasStartFormKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.SUSPENSION_STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer suspensionState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.VERSION_TAG_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String versionTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.HISTORY_TTL_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer historyTtl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.STARTABLE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Boolean startable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.ID_
     *
     * @return the value of act_re_procdef.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.ID_
     *
     * @param id the value for act_re_procdef.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.REV_
     *
     * @return the value of act_re_procdef.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.REV_
     *
     * @param rev the value for act_re_procdef.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.CATEGORY_
     *
     * @return the value of act_re_procdef.CATEGORY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.CATEGORY_
     *
     * @param category the value for act_re_procdef.CATEGORY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.NAME_
     *
     * @return the value of act_re_procdef.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.NAME_
     *
     * @param name the value for act_re_procdef.NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.KEY_
     *
     * @return the value of act_re_procdef.KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.KEY_
     *
     * @param key the value for act_re_procdef.KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.VERSION_
     *
     * @return the value of act_re_procdef.VERSION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.VERSION_
     *
     * @param version the value for act_re_procdef.VERSION_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.DEPLOYMENT_ID_
     *
     * @return the value of act_re_procdef.DEPLOYMENT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.DEPLOYMENT_ID_
     *
     * @param deploymentId the value for act_re_procdef.DEPLOYMENT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId == null ? null : deploymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.RESOURCE_NAME_
     *
     * @return the value of act_re_procdef.RESOURCE_NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.RESOURCE_NAME_
     *
     * @param resourceName the value for act_re_procdef.RESOURCE_NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @return the value of act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getDgrmResourceName() {
        return dgrmResourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @param dgrmResourceName the value for act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setDgrmResourceName(String dgrmResourceName) {
        this.dgrmResourceName = dgrmResourceName == null ? null : dgrmResourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.HAS_START_FORM_KEY_
     *
     * @return the value of act_re_procdef.HAS_START_FORM_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Byte getHasStartFormKey() {
        return hasStartFormKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.HAS_START_FORM_KEY_
     *
     * @param hasStartFormKey the value for act_re_procdef.HAS_START_FORM_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setHasStartFormKey(Byte hasStartFormKey) {
        this.hasStartFormKey = hasStartFormKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.SUSPENSION_STATE_
     *
     * @return the value of act_re_procdef.SUSPENSION_STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getSuspensionState() {
        return suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.SUSPENSION_STATE_
     *
     * @param suspensionState the value for act_re_procdef.SUSPENSION_STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setSuspensionState(Integer suspensionState) {
        this.suspensionState = suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.TENANT_ID_
     *
     * @return the value of act_re_procdef.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.TENANT_ID_
     *
     * @param tenantId the value for act_re_procdef.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.VERSION_TAG_
     *
     * @return the value of act_re_procdef.VERSION_TAG_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getVersionTag() {
        return versionTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.VERSION_TAG_
     *
     * @param versionTag the value for act_re_procdef.VERSION_TAG_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setVersionTag(String versionTag) {
        this.versionTag = versionTag == null ? null : versionTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.HISTORY_TTL_
     *
     * @return the value of act_re_procdef.HISTORY_TTL_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getHistoryTtl() {
        return historyTtl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.HISTORY_TTL_
     *
     * @param historyTtl the value for act_re_procdef.HISTORY_TTL_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setHistoryTtl(Integer historyTtl) {
        this.historyTtl = historyTtl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.STARTABLE_
     *
     * @return the value of act_re_procdef.STARTABLE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Boolean getStartable() {
        return startable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.STARTABLE_
     *
     * @param startable the value for act_re_procdef.STARTABLE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setStartable(Boolean startable) {
        this.startable = startable;
    }
}