package com.nyuen.camunda.domain.po;

public class ActRuExecution {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String rootProcInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.BUSINESS_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String businessKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.PARENT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.SUPER_EXEC_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String superExec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.SUPER_CASE_EXEC_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String superCaseExec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String caseInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.ACT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String actId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.ACT_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String actInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.IS_ACTIVE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Byte isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.IS_CONCURRENT_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Byte isConcurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.IS_SCOPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Byte isScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.IS_EVENT_SCOPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Byte isEventScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.SUSPENSION_STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer suspensionState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.CACHED_ENT_STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Integer cachedEntState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.SEQUENCE_COUNTER_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private Long sequenceCounter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.ID_
     *
     * @return the value of act_ru_execution.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.ID_
     *
     * @param id the value for act_ru_execution.ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.REV_
     *
     * @return the value of act_ru_execution.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.REV_
     *
     * @param rev the value for act_ru_execution.REV_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.ROOT_PROC_INST_ID_
     *
     * @return the value of act_ru_execution.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getRootProcInstId() {
        return rootProcInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.ROOT_PROC_INST_ID_
     *
     * @param rootProcInstId the value for act_ru_execution.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setRootProcInstId(String rootProcInstId) {
        this.rootProcInstId = rootProcInstId == null ? null : rootProcInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.PROC_INST_ID_
     *
     * @return the value of act_ru_execution.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.PROC_INST_ID_
     *
     * @param procInstId the value for act_ru_execution.PROC_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.BUSINESS_KEY_
     *
     * @return the value of act_ru_execution.BUSINESS_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getBusinessKey() {
        return businessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.BUSINESS_KEY_
     *
     * @param businessKey the value for act_ru_execution.BUSINESS_KEY_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey == null ? null : businessKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.PARENT_ID_
     *
     * @return the value of act_ru_execution.PARENT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.PARENT_ID_
     *
     * @param parentId the value for act_ru_execution.PARENT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.PROC_DEF_ID_
     *
     * @return the value of act_ru_execution.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.PROC_DEF_ID_
     *
     * @param procDefId the value for act_ru_execution.PROC_DEF_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.SUPER_EXEC_
     *
     * @return the value of act_ru_execution.SUPER_EXEC_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getSuperExec() {
        return superExec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.SUPER_EXEC_
     *
     * @param superExec the value for act_ru_execution.SUPER_EXEC_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setSuperExec(String superExec) {
        this.superExec = superExec == null ? null : superExec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.SUPER_CASE_EXEC_
     *
     * @return the value of act_ru_execution.SUPER_CASE_EXEC_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getSuperCaseExec() {
        return superCaseExec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.SUPER_CASE_EXEC_
     *
     * @param superCaseExec the value for act_ru_execution.SUPER_CASE_EXEC_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setSuperCaseExec(String superCaseExec) {
        this.superCaseExec = superCaseExec == null ? null : superCaseExec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.CASE_INST_ID_
     *
     * @return the value of act_ru_execution.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getCaseInstId() {
        return caseInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.CASE_INST_ID_
     *
     * @param caseInstId the value for act_ru_execution.CASE_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCaseInstId(String caseInstId) {
        this.caseInstId = caseInstId == null ? null : caseInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.ACT_ID_
     *
     * @return the value of act_ru_execution.ACT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.ACT_ID_
     *
     * @param actId the value for act_ru_execution.ACT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setActId(String actId) {
        this.actId = actId == null ? null : actId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.ACT_INST_ID_
     *
     * @return the value of act_ru_execution.ACT_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getActInstId() {
        return actInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.ACT_INST_ID_
     *
     * @param actInstId the value for act_ru_execution.ACT_INST_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setActInstId(String actInstId) {
        this.actInstId = actInstId == null ? null : actInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.IS_ACTIVE_
     *
     * @return the value of act_ru_execution.IS_ACTIVE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Byte getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.IS_ACTIVE_
     *
     * @param isActive the value for act_ru_execution.IS_ACTIVE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.IS_CONCURRENT_
     *
     * @return the value of act_ru_execution.IS_CONCURRENT_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Byte getIsConcurrent() {
        return isConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.IS_CONCURRENT_
     *
     * @param isConcurrent the value for act_ru_execution.IS_CONCURRENT_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setIsConcurrent(Byte isConcurrent) {
        this.isConcurrent = isConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.IS_SCOPE_
     *
     * @return the value of act_ru_execution.IS_SCOPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Byte getIsScope() {
        return isScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.IS_SCOPE_
     *
     * @param isScope the value for act_ru_execution.IS_SCOPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setIsScope(Byte isScope) {
        this.isScope = isScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.IS_EVENT_SCOPE_
     *
     * @return the value of act_ru_execution.IS_EVENT_SCOPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Byte getIsEventScope() {
        return isEventScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.IS_EVENT_SCOPE_
     *
     * @param isEventScope the value for act_ru_execution.IS_EVENT_SCOPE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setIsEventScope(Byte isEventScope) {
        this.isEventScope = isEventScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.SUSPENSION_STATE_
     *
     * @return the value of act_ru_execution.SUSPENSION_STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getSuspensionState() {
        return suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.SUSPENSION_STATE_
     *
     * @param suspensionState the value for act_ru_execution.SUSPENSION_STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setSuspensionState(Integer suspensionState) {
        this.suspensionState = suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.CACHED_ENT_STATE_
     *
     * @return the value of act_ru_execution.CACHED_ENT_STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Integer getCachedEntState() {
        return cachedEntState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.CACHED_ENT_STATE_
     *
     * @param cachedEntState the value for act_ru_execution.CACHED_ENT_STATE_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setCachedEntState(Integer cachedEntState) {
        this.cachedEntState = cachedEntState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.SEQUENCE_COUNTER_
     *
     * @return the value of act_ru_execution.SEQUENCE_COUNTER_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public Long getSequenceCounter() {
        return sequenceCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.SEQUENCE_COUNTER_
     *
     * @param sequenceCounter the value for act_ru_execution.SEQUENCE_COUNTER_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setSequenceCounter(Long sequenceCounter) {
        this.sequenceCounter = sequenceCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.TENANT_ID_
     *
     * @return the value of act_ru_execution.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.TENANT_ID_
     *
     * @param tenantId the value for act_ru_execution.TENANT_ID_
     *
     * @mbg.generated Tue Sep 06 10:38:43 CST 2022
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }
}