package com.nyuen.camunda.domain.po;

import java.util.Date;

public class ExperimentData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_data.id
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_data.proc_def_id
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_data.node_name
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    private String nodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_data.file_name
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_data.url
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_data.create_user
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_data.create_time
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_data.download_count
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    private Integer downloadCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_data.status
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_data.remark
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_data.id
     *
     * @return the value of experiment_data.id
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_data.id
     *
     * @param id the value for experiment_data.id
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_data.proc_def_id
     *
     * @return the value of experiment_data.proc_def_id
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_data.proc_def_id
     *
     * @param procDefId the value for experiment_data.proc_def_id
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_data.node_name
     *
     * @return the value of experiment_data.node_name
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_data.node_name
     *
     * @param nodeName the value for experiment_data.node_name
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_data.file_name
     *
     * @return the value of experiment_data.file_name
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_data.file_name
     *
     * @param fileName the value for experiment_data.file_name
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_data.url
     *
     * @return the value of experiment_data.url
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_data.url
     *
     * @param url the value for experiment_data.url
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_data.create_user
     *
     * @return the value of experiment_data.create_user
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_data.create_user
     *
     * @param createUser the value for experiment_data.create_user
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_data.create_time
     *
     * @return the value of experiment_data.create_time
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_data.create_time
     *
     * @param createTime the value for experiment_data.create_time
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_data.download_count
     *
     * @return the value of experiment_data.download_count
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public Integer getDownloadCount() {
        return downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_data.download_count
     *
     * @param downloadCount the value for experiment_data.download_count
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public void setDownloadCount(Integer downloadCount) {
        this.downloadCount = downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_data.status
     *
     * @return the value of experiment_data.status
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_data.status
     *
     * @param status the value for experiment_data.status
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_data.remark
     *
     * @return the value of experiment_data.remark
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_data.remark
     *
     * @param remark the value for experiment_data.remark
     *
     * @mbg.generated Mon Nov 21 09:57:28 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}