package com.nyuen.camunda.domain.po;

import java.util.Date;

public class LabFridge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge.id
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge.fridge_no
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    private String fridgeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge.fridge_state
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    private Integer fridgeState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge.remark
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge.create_user_id
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge.create_user_name
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge.create_time
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge.id
     *
     * @return the value of lab_fridge.id
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge.id
     *
     * @param id the value for lab_fridge.id
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge.fridge_no
     *
     * @return the value of lab_fridge.fridge_no
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public String getFridgeNo() {
        return fridgeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge.fridge_no
     *
     * @param fridgeNo the value for lab_fridge.fridge_no
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public void setFridgeNo(String fridgeNo) {
        this.fridgeNo = fridgeNo == null ? null : fridgeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge.fridge_state
     *
     * @return the value of lab_fridge.fridge_state
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public Integer getFridgeState() {
        return fridgeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge.fridge_state
     *
     * @param fridgeState the value for lab_fridge.fridge_state
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public void setFridgeState(Integer fridgeState) {
        this.fridgeState = fridgeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge.remark
     *
     * @return the value of lab_fridge.remark
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge.remark
     *
     * @param remark the value for lab_fridge.remark
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge.create_user_id
     *
     * @return the value of lab_fridge.create_user_id
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge.create_user_id
     *
     * @param createUserId the value for lab_fridge.create_user_id
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge.create_user_name
     *
     * @return the value of lab_fridge.create_user_name
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge.create_user_name
     *
     * @param createUserName the value for lab_fridge.create_user_name
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge.create_time
     *
     * @return the value of lab_fridge.create_time
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge.create_time
     *
     * @param createTime the value for lab_fridge.create_time
     *
     * @mbg.generated Mon Feb 20 14:48:00 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
