package com.nyuen.camunda.domain.po;

import java.util.Date;

public class LabFridgeLevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge_level.id
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge_level.fridge_no
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    private String fridgeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge_level.level_no
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    private Integer levelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge_level.box_no
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    private String boxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge_level.box_index
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    private Integer boxIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge_level.sample_type
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    private String sampleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge_level.remark
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge_level.create_user_id
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge_level.create_user_name
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_fridge_level.create_time
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge_level.id
     *
     * @return the value of lab_fridge_level.id
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge_level.id
     *
     * @param id the value for lab_fridge_level.id
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge_level.fridge_no
     *
     * @return the value of lab_fridge_level.fridge_no
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public String getFridgeNo() {
        return fridgeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge_level.fridge_no
     *
     * @param fridgeNo the value for lab_fridge_level.fridge_no
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public void setFridgeNo(String fridgeNo) {
        this.fridgeNo = fridgeNo == null ? null : fridgeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge_level.level_no
     *
     * @return the value of lab_fridge_level.level_no
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public Integer getLevelNo() {
        return levelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge_level.level_no
     *
     * @param levelNo the value for lab_fridge_level.level_no
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public void setLevelNo(Integer levelNo) {
        this.levelNo = levelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge_level.box_no
     *
     * @return the value of lab_fridge_level.box_no
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public String getBoxNo() {
        return boxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge_level.box_no
     *
     * @param boxNo the value for lab_fridge_level.box_no
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public void setBoxNo(String boxNo) {
        this.boxNo = boxNo == null ? null : boxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge_level.box_index
     *
     * @return the value of lab_fridge_level.box_index
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public Integer getBoxIndex() {
        return boxIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge_level.box_index
     *
     * @param boxIndex the value for lab_fridge_level.box_index
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public void setBoxIndex(Integer boxIndex) {
        this.boxIndex = boxIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge_level.sample_type
     *
     * @return the value of lab_fridge_level.sample_type
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public String getSampleType() {
        return sampleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge_level.sample_type
     *
     * @param sampleType the value for lab_fridge_level.sample_type
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public void setSampleType(String sampleType) {
        this.sampleType = sampleType == null ? null : sampleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge_level.remark
     *
     * @return the value of lab_fridge_level.remark
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge_level.remark
     *
     * @param remark the value for lab_fridge_level.remark
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge_level.create_user_id
     *
     * @return the value of lab_fridge_level.create_user_id
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge_level.create_user_id
     *
     * @param createUserId the value for lab_fridge_level.create_user_id
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge_level.create_user_name
     *
     * @return the value of lab_fridge_level.create_user_name
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge_level.create_user_name
     *
     * @param createUserName the value for lab_fridge_level.create_user_name
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_fridge_level.create_time
     *
     * @return the value of lab_fridge_level.create_time
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_fridge_level.create_time
     *
     * @param createTime the value for lab_fridge_level.create_time
     *
     * @mbg.generated Thu Apr 06 14:19:05 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
