package com.nyuen.camunda.domain.po;

import java.util.Date;

public class NyuenResultCheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nyuen_result_check.id
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nyuen_result_check.sample_info
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    private String sampleInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nyuen_result_check.assay_id
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    private String assayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nyuen_result_check.assay_type
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    private String assayType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nyuen_result_check.snp
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    private String snp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nyuen_result_check.call_result
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    private String callResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nyuen_result_check.create_user_id
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nyuen_result_check.create_user
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nyuen_result_check.create_time
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nyuen_result_check.id
     *
     * @return the value of nyuen_result_check.id
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nyuen_result_check.id
     *
     * @param id the value for nyuen_result_check.id
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nyuen_result_check.sample_info
     *
     * @return the value of nyuen_result_check.sample_info
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public String getSampleInfo() {
        return sampleInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nyuen_result_check.sample_info
     *
     * @param sampleInfo the value for nyuen_result_check.sample_info
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public void setSampleInfo(String sampleInfo) {
        this.sampleInfo = sampleInfo == null ? null : sampleInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nyuen_result_check.assay_id
     *
     * @return the value of nyuen_result_check.assay_id
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public String getAssayId() {
        return assayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nyuen_result_check.assay_id
     *
     * @param assayId the value for nyuen_result_check.assay_id
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public void setAssayId(String assayId) {
        this.assayId = assayId == null ? null : assayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nyuen_result_check.assay_type
     *
     * @return the value of nyuen_result_check.assay_type
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public String getAssayType() {
        return assayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nyuen_result_check.assay_type
     *
     * @param assayType the value for nyuen_result_check.assay_type
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public void setAssayType(String assayType) {
        this.assayType = assayType == null ? null : assayType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nyuen_result_check.snp
     *
     * @return the value of nyuen_result_check.snp
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public String getSnp() {
        return snp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nyuen_result_check.snp
     *
     * @param snp the value for nyuen_result_check.snp
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public void setSnp(String snp) {
        this.snp = snp == null ? null : snp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nyuen_result_check.call_result
     *
     * @return the value of nyuen_result_check.call_result
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public String getCallResult() {
        return callResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nyuen_result_check.call_result
     *
     * @param callResult the value for nyuen_result_check.call_result
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public void setCallResult(String callResult) {
        this.callResult = callResult == null ? null : callResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nyuen_result_check.create_user_id
     *
     * @return the value of nyuen_result_check.create_user_id
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nyuen_result_check.create_user_id
     *
     * @param createUserId the value for nyuen_result_check.create_user_id
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nyuen_result_check.create_user
     *
     * @return the value of nyuen_result_check.create_user
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nyuen_result_check.create_user
     *
     * @param createUser the value for nyuen_result_check.create_user
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nyuen_result_check.create_time
     *
     * @return the value of nyuen_result_check.create_time
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nyuen_result_check.create_time
     *
     * @param createTime the value for nyuen_result_check.create_time
     *
     * @mbg.generated Mon Dec 26 16:47:42 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}