package com.nyuen.camunda.domain.po;

import java.util.Date;

public class SampleTypeSavePeriod {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_type_save_period.id
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_type_save_period.sample_type
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private String sampleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_type_save_period.save_period
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private Integer savePeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_type_save_period.create_user_id
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_type_save_period.create_user_name
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_type_save_period.create_time
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_type_save_period.remark
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_type_save_period.remark1
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private String remark1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_type_save_period.id
     *
     * @return the value of sample_type_save_period.id
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_type_save_period.id
     *
     * @param id the value for sample_type_save_period.id
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_type_save_period.sample_type
     *
     * @return the value of sample_type_save_period.sample_type
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public String getSampleType() {
        return sampleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_type_save_period.sample_type
     *
     * @param sampleType the value for sample_type_save_period.sample_type
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setSampleType(String sampleType) {
        this.sampleType = sampleType == null ? null : sampleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_type_save_period.save_period
     *
     * @return the value of sample_type_save_period.save_period
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public Integer getSavePeriod() {
        return savePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_type_save_period.save_period
     *
     * @param savePeriod the value for sample_type_save_period.save_period
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setSavePeriod(Integer savePeriod) {
        this.savePeriod = savePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_type_save_period.create_user_id
     *
     * @return the value of sample_type_save_period.create_user_id
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_type_save_period.create_user_id
     *
     * @param createUserId the value for sample_type_save_period.create_user_id
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_type_save_period.create_user_name
     *
     * @return the value of sample_type_save_period.create_user_name
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_type_save_period.create_user_name
     *
     * @param createUserName the value for sample_type_save_period.create_user_name
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_type_save_period.create_time
     *
     * @return the value of sample_type_save_period.create_time
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_type_save_period.create_time
     *
     * @param createTime the value for sample_type_save_period.create_time
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_type_save_period.remark
     *
     * @return the value of sample_type_save_period.remark
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_type_save_period.remark
     *
     * @param remark the value for sample_type_save_period.remark
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_type_save_period.remark1
     *
     * @return the value of sample_type_save_period.remark1
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_type_save_period.remark1
     *
     * @param remark1 the value for sample_type_save_period.remark1
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }
}
