package com.nyuen.camunda.domain.po;

import java.util.Date;

public class SampleStorageOperation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_storage_operation.id
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_storage_operation.sample_num
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private String sampleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_storage_operation.operate_user_id
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private Long operateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_storage_operation.operate_user_name
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private String operateUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_storage_operation.operate_type
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private String operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_storage_operation.operation
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_storage_operation.operate_time
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_storage_operation.remark
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_storage_operation.remark1
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    private String remark1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_storage_operation.id
     *
     * @return the value of sample_storage_operation.id
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_storage_operation.id
     *
     * @param id the value for sample_storage_operation.id
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_storage_operation.sample_num
     *
     * @return the value of sample_storage_operation.sample_num
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public String getSampleNum() {
        return sampleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_storage_operation.sample_num
     *
     * @param sampleNum the value for sample_storage_operation.sample_num
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setSampleNum(String sampleNum) {
        this.sampleNum = sampleNum == null ? null : sampleNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_storage_operation.operate_user_id
     *
     * @return the value of sample_storage_operation.operate_user_id
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public Long getOperateUserId() {
        return operateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_storage_operation.operate_user_id
     *
     * @param operateUserId the value for sample_storage_operation.operate_user_id
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setOperateUserId(Long operateUserId) {
        this.operateUserId = operateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_storage_operation.operate_user_name
     *
     * @return the value of sample_storage_operation.operate_user_name
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public String getOperateUserName() {
        return operateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_storage_operation.operate_user_name
     *
     * @param operateUserName the value for sample_storage_operation.operate_user_name
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setOperateUserName(String operateUserName) {
        this.operateUserName = operateUserName == null ? null : operateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_storage_operation.operate_type
     *
     * @return the value of sample_storage_operation.operate_type
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_storage_operation.operate_type
     *
     * @param operateType the value for sample_storage_operation.operate_type
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_storage_operation.operation
     *
     * @return the value of sample_storage_operation.operation
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_storage_operation.operation
     *
     * @param operation the value for sample_storage_operation.operation
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_storage_operation.operate_time
     *
     * @return the value of sample_storage_operation.operate_time
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_storage_operation.operate_time
     *
     * @param operateTime the value for sample_storage_operation.operate_time
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_storage_operation.remark
     *
     * @return the value of sample_storage_operation.remark
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_storage_operation.remark
     *
     * @param remark the value for sample_storage_operation.remark
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_storage_operation.remark1
     *
     * @return the value of sample_storage_operation.remark1
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_storage_operation.remark1
     *
     * @param remark1 the value for sample_storage_operation.remark1
     *
     * @mbg.generated Mon Feb 20 11:10:43 CST 2023
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }
}
