package com.nyuen.camunda.domain.po;

import java.util.Date;

public class SampleLabInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.id
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.sample_info
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private String sampleInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.batch
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private Integer batch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.batch_code
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private String batchCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.assignee
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private String assignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.proc_def_id
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.proc_inst_id
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.node_name
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private String nodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.initiator
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private String initiator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.product_type
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private Integer productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.product_name
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.hole_num
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private Integer holeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.hole_code
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private String holeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.assay_code
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private String assayCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.state
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.create_user_id
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.create_user_name
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.create_time
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_lab_info.remark
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.id
     *
     * @return the value of sample_lab_info.id
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.id
     *
     * @param id the value for sample_lab_info.id
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.sample_info
     *
     * @return the value of sample_lab_info.sample_info
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public String getSampleInfo() {
        return sampleInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.sample_info
     *
     * @param sampleInfo the value for sample_lab_info.sample_info
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setSampleInfo(String sampleInfo) {
        this.sampleInfo = sampleInfo == null ? null : sampleInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.batch
     *
     * @return the value of sample_lab_info.batch
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public Integer getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.batch
     *
     * @param batch the value for sample_lab_info.batch
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setBatch(Integer batch) {
        this.batch = batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.batch_code
     *
     * @return the value of sample_lab_info.batch_code
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public String getBatchCode() {
        return batchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.batch_code
     *
     * @param batchCode the value for sample_lab_info.batch_code
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setBatchCode(String batchCode) {
        this.batchCode = batchCode == null ? null : batchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.assignee
     *
     * @return the value of sample_lab_info.assignee
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public String getAssignee() {
        return assignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.assignee
     *
     * @param assignee the value for sample_lab_info.assignee
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee == null ? null : assignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.proc_def_id
     *
     * @return the value of sample_lab_info.proc_def_id
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.proc_def_id
     *
     * @param procDefId the value for sample_lab_info.proc_def_id
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.proc_inst_id
     *
     * @return the value of sample_lab_info.proc_inst_id
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.proc_inst_id
     *
     * @param procInstId the value for sample_lab_info.proc_inst_id
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.node_name
     *
     * @return the value of sample_lab_info.node_name
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.node_name
     *
     * @param nodeName the value for sample_lab_info.node_name
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.initiator
     *
     * @return the value of sample_lab_info.initiator
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public String getInitiator() {
        return initiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.initiator
     *
     * @param initiator the value for sample_lab_info.initiator
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setInitiator(String initiator) {
        this.initiator = initiator == null ? null : initiator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.product_type
     *
     * @return the value of sample_lab_info.product_type
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.product_type
     *
     * @param productType the value for sample_lab_info.product_type
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.product_name
     *
     * @return the value of sample_lab_info.product_name
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.product_name
     *
     * @param productName the value for sample_lab_info.product_name
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.hole_num
     *
     * @return the value of sample_lab_info.hole_num
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public Integer getHoleNum() {
        return holeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.hole_num
     *
     * @param holeNum the value for sample_lab_info.hole_num
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setHoleNum(Integer holeNum) {
        this.holeNum = holeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.hole_code
     *
     * @return the value of sample_lab_info.hole_code
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public String getHoleCode() {
        return holeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.hole_code
     *
     * @param holeCode the value for sample_lab_info.hole_code
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setHoleCode(String holeCode) {
        this.holeCode = holeCode == null ? null : holeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.assay_code
     *
     * @return the value of sample_lab_info.assay_code
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public String getAssayCode() {
        return assayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.assay_code
     *
     * @param assayCode the value for sample_lab_info.assay_code
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setAssayCode(String assayCode) {
        this.assayCode = assayCode == null ? null : assayCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.state
     *
     * @return the value of sample_lab_info.state
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.state
     *
     * @param state the value for sample_lab_info.state
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.create_user_id
     *
     * @return the value of sample_lab_info.create_user_id
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.create_user_id
     *
     * @param createUserId the value for sample_lab_info.create_user_id
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.create_user_name
     *
     * @return the value of sample_lab_info.create_user_name
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.create_user_name
     *
     * @param createUserName the value for sample_lab_info.create_user_name
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.create_time
     *
     * @return the value of sample_lab_info.create_time
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.create_time
     *
     * @param createTime the value for sample_lab_info.create_time
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_lab_info.remark
     *
     * @return the value of sample_lab_info.remark
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_lab_info.remark
     *
     * @param remark the value for sample_lab_info.remark
     *
     * @mbg.generated Tue Nov 29 14:09:32 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}